services:
  - type: web
    name: deep-fake-analysis
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && gunicorn --worker-class gthread --threads 4 --timeout 600 -w 1 -b 0.0.0.0:$PORT api:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false
